=== BayanGroup/nutch-custom-search/zal.extractor/src/main/resources/extractors.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://bayan.ir" xmlns="http://bayan.ir">

	<xs:complexType name="typeType">
		<xs:attribute type="xs:ID" name="name" use="required" />
		<xs:attribute type="xs:string" name="converter" use="optional" />
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:attribute type="xs:ID" name="name" use="required" />
		<xs:attribute type="xs:IDREF" name="type" use="optional" />
	</xs:complexType>
	
	<xs:group name="functions">
		<xs:choice>
			<xs:element name="expr" type="exprType"/>
			<xs:element name="constant" type="constantType"/>
			<xs:element name="concat" type="concatType" />
			<xs:element name="replace" type="replaceType" />
			<xs:element name="text" type="textType" />
			<xs:element name="attribute" type="attributeType" />
			<xs:element name="first" type="firstType" />
			<xs:element name="last" type="lastType" />
			<xs:element name="size" type="sizeType" />
			<xs:element name="url" type="urlType" />
			<xs:element name="resolve" type="resolveType" />
		</xs:choice>
	</xs:group>
	
	<xs:complexType name="functionType">
		<xs:sequence>
			<xs:group ref="functions" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="singleFunctionType">
		<xs:sequence>
			<xs:group ref="functions" minOccurs="1" maxOccurs="1"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="exprType">
		<xs:annotation>
			<xs:documentation source="description">
				Evaluates an expression using current engine.
			</xs:documentation>
		</xs:annotation>
		<xs:attribute name="value" use="required">
			<xs:annotation>
			<xs:documentation source="description">
				The expression which is understandable by current engine.
			</xs:documentation>
		</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	
	<xs:complexType name="constantType">
		<xs:attribute name="value" use="required"/>
	</xs:complexType>
	
	<xs:complexType name="concatType">
		<xs:annotation>
			<xs:documentation source="description">
				Concats its inputs by the provided delimiter.
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="functionType">
				<xs:attribute name="delimiter" default=" "/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="replaceType">
		<xs:annotation>
			<xs:documentation source="description">
				Replaces its input using the provided regex pattern by the provided substitution.
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
				<xs:attribute name="pattern" use="required"/>
				<xs:attribute name="substitution" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="textType">
		<xs:annotation>
			<xs:documentation source="description">
				Returns the text content of its input.
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="attributeType">
		<xs:annotation>
			<xs:documentation source="description">
				Extracts the value of attribute with specified name from underling elements.
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
				<xs:attribute name="name" use="required"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="firstType">
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="lastType">
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="sizeType">
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="urlType">
		<xs:annotation>
			<xs:documentation source="description">
				Returns the current url in the context.
			</xs:documentation>
		</xs:annotation>
		<xs:simpleContent>
			<xs:extension base="xs:string"></xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	
	<xs:complexType name="resolveType">
		<xs:annotation>
			<xs:documentation source="description">
				 Resolves a possible relative url to absolute one based on the current url in the context.
			</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="extractToType">
		<xs:complexContent>
			<xs:extension base="singleFunctionType">
				<xs:attribute type="xs:IDREF" name="field" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="fragmentType">
		<xs:sequence>
			<xs:element name="outlinks" type="outlinksType" minOccurs="0" maxOccurs="1"/>
			<xs:element name="extract-to" type="extractToType" minOccurs="0" maxOccurs="unbounded"/>
		</xs:sequence>
		<xs:attribute name="root" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="linkType">
		
		<xs:all>
			<xs:element name="href" type="singleFunctionType" minOccurs="1"/>
			<xs:element name="anchor" type="singleFunctionType" minOccurs="0"/>
		</xs:all>
		<xs:attribute name="root" type="xs:string"/>
	</xs:complexType>
	
	<xs:complexType name="outlinksType">
		<xs:sequence>
			<xs:element name="link" type="linkType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="documentType">
		<xs:sequence>
			<xs:element name="outlinks" type="outlinksType" minOccurs="0" maxOccurs="1"/>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="fragment" type="fragmentType" minOccurs="0" maxOccurs="1"/>
				<xs:element name="extract-to" type="extractToType" minOccurs="0" maxOccurs="1"/>
			</xs:choice>
		</xs:sequence>
		<xs:attribute type="xs:ID" name="id" use="optional" />
		<xs:attribute type="xs:string" name="url" use="optional" />
		<xs:attribute type="xs:string" name="contentType" use="optional" />
		<xs:attribute type="xs:IDREF" name="inherits" use="optional" />
		<xs:attribute type="xs:string" name="engine" use="optional" default="css"/>
		<xs:attribute name="root" type="xs:string"/>
	</xs:complexType>

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="types">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type" maxOccurs="unbounded" minOccurs="0" type="typeType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0" type="fieldType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="documents">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="document" maxOccurs="unbounded" minOccurs="0" type="documentType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="omitNonMatching" type="xs:boolean" default="true"/>
			<xs:attribute name="defaultEngine" type="xs:string" default="css"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BayanGroup/nutch-custom-search/zal.extractor/src/main/resources/extractors.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd"
	omitNonMatching="true">
	<types>
		<type name="long" converter="ir.co.bayan.simorq.zal.extractor.convert.LongConverter" />
		<type name="date" converter="ir.co.bayan.simorq.zal.extractor.convert.DateConverter" />
		<type name="date-time" converter="ir.co.bayan.simorq.zal.extractor.convert.DateTimeConverter" />
		<type name="persian-date" converter="ir.co.bayan.simorq.zal.extractor.convert.PersianDateConverter"/>
	</types>
	<fields>
		<field name="post-title" />
		<field name="post-blog-title" />
		<field name="post-body" />
		<field name="post-comments" />
		<field name="post-comments-num" type="long" />
		<field name="post-categories" />
		
		<field name="blog-title" />
		<field name="blog-sub-title" />
		<field name="blog-desc" />
		<field name="blog-total-visits" type="long"/>
		
		<field name="keywords" />
		<field name="description" />
		<field name="modification-date" type="date-time"/>
		<field name="author" />
		<field name="document-type" />
		<field name="csi" />
		<field name="url"/>
		<field name="title" />
		<field name="content" />
	</fields>
	<documents>
		<document id="blog-ir">
			<extract-to field="csi">
				<constant value="1"/>
			</extract-to>
		</document>
		<document id="blog-ir-page" inherits="blog-ir">
			<extract-to field="title">
				<text>
					<expr value="title" />
				</text>
			</extract-to>
			<extract-to field="blog-total-visits">
				<text>
					<expr value="#value_VIEW_STAT_TOTAL"/>
				</text>
			</extract-to>
			<extract-to field="author">
				<trim>
					<text>
						<first>
							<expr value="span.author, span.author2"/>
						</first>
					</text>
				</trim>
			</extract-to>
		</document>
		<document id="blog-ir-post-page" inherits="blog-ir-page">
			<extract-to field="post-title">
				<trim>
					<replace pattern="(.+?) :: (.+)" substitution="$2">
						<text>
							<expr value="title"/>
						</text>
					</replace>
				</trim>
			</extract-to>
			<extract-to field="post-blog-title">
				<trim>
					<replace pattern="(.+?) :: (.+)" substitution="$1">
						<text>
							<expr value="title"/>
						</text>
					</replace>
				</trim>
			</extract-to>
			<extract-to field="post-body">
				<text>
					<expr value=".post .body .cnt"/>
				</text>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir/((\d{4}/\d{2})|post)/.+" inherits="blog-ir-post-page" engine="css" update="false">
			<extract-to field="modification-date" >
				<attribute name="content">
					<expr value="meta[name=date]"/>
				</attribute>
			</extract-to>
			<extract-to field="post-comments">
				<concat>
					<text>
						<expr value=".post_comments .body_cmt .cnt span.cnt_l"/>
					</text>
					<replace pattern="^(پاسخ:)?(.*)" substitution="$2">
						<text>
							<expr value=".cmt_reply"/>
						</text>
					</replace>
				</concat>
			</extract-to>
			<extract-to field="keywords">
				<trim>
					<text>
						<expr value=".keywords_post h3"/>
					</text>
				</trim>
			</extract-to>
			<extract-to field="document-type">
				<constant value="Post"/>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir/page/.+" inherits="blog-ir-post-page">
			<extract-to field="document-type">
				<constant value="Custom-Page"/>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir/?" inherits="blog-ir-page">
			<outlinks>
				<!-- 
				<link>
					<href>
						<concat delimiter="">
							<url />
							<constant value="rss/" />
						</concat>
					</href>
				</link> -->
				<link>
					<href>
						<concat delimiter="">
							<url />
							<constant value="sitemap.xml" />
						</concat>
					</href>
				</link>
			</outlinks>
			<extract-to field="blog-title">
				<trim>
					<text>
						<expr value="title"/>
					</text>
				</trim>
			</extract-to>
			<extract-to field="blog-sub-title">
				<text>
					<expr value="div.desc h2"/>
				</text>
			</extract-to>
			<extract-to field="blog-desc">
				<text>
					<expr value=".blog_description h4"/>
				</text>
			</extract-to>
			<extract-to field="keywords">
				<trim>
					<text>
						<expr value=".tagcloud a h3, .tagcloud h3 a"/>
					</text>
				</trim>
			</extract-to>
			<extract-to field="document-type">
				<constant value="First-Page"/>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir/sitemap.xml" engine="xpath">
			<outlinks>
				<for-each root="dns:url"> 
					<link>
						<href>
							<text>
								<expr value="./dns:loc" />
							</text>
						</href>
						<anchor>
							<text>
								<expr value="./blog:dloc" />
							</text>
						</anchor>
					</link>
				</for-each>
			</outlinks>			
		</document>
		<!-- 
		<document url="^http://.+?\.blog.ir/rss.*" engine="xpath" root="//item" inherits="blog-ir" update="true">
			<extract-to field="url">
				<text>
					<expr value="./link" />
				</text>
			</extract-to>
			<extract-to field="author">
				<text>
					<expr value="./dc:creator" />
				</text>
			</extract-to>
			<extract-to field="keywords">
				<trim>
					<text>
						<expr value="./category" />
					</text>
				</trim>
			</extract-to>
			<extract-to field="post-comments-num">
				<text>
					<expr value="./slash:comments"/>
				</text>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir/category/.*" engine="css" root=".post" inherits="blog-ir" update="true">
			<extract-to field="url">
				<resolve>
					<attribute name="href">
						<expr value=".title a" />
					</attribute>
				</resolve>
			</extract-to>
			<extract-to field="post-categories">
				<replace substitution="^http://.+?\.blog.ir/category/(.+?)/?" pattern="$1">
					<url />
				</replace>
			</extract-to>
		</document>
		<document url="http://blog.ir/changes" engine="css">
			<outlinks>
				<for-each root=".post">
					<link>
						<href>
							<attribute name="href">
								<expr value="a" />
							</attribute>
						</href>
					</link>
				</for-each>	
			</outlinks>				
		</document>
		 -->
	</documents>
</config>

=== BayanGroup/nutch-custom-search/zal.nutch.extractor/src/test/resources/extractors-selector-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd">
	<types>
		<type name="hello" converter="ir.co.bayan.simorq.zal.nutch.extractor.TestConverter" />
	</types>
	<fields>
		<field name="f1" />
		<field name="f2" />
		<field name="f3" />
		<field name="f4" />
		<field name="f5" />
		
		<field name="f6" />
		<field name="f6.1" />
		
		<field name="f7" />
		<field name="f8" />
		<field name="f9" />
		<field name="f10" />
		
		<field name="f11" />
		
		<field name="f12" type="hello"/>
		
		<field name="id" />
		<field name="content" />
	</fields>
	<documents>
		<document id="base" url="^http://.+?\.blog.ir">
			<extract-to field="f1">
				<constant value="t1"/>
			</extract-to>
			<extract-to field="f2">
				<concat>
					<text>
						<expr value="head > title"/>
					</text>
				</concat>
			</extract-to>
			<extract-to field="f3">
				<concat>
					<attribute name="title">
						<expr value=".title-div"/>
					</attribute>
				</concat>
			</extract-to>
			<extract-to field="f4">
				<url />
			</extract-to>
			
			<extract-to field="f5">
				<concat>
					<constant value="t1"/>
					<text>
						<expr value="head > title"/>
					</text>
					<attribute name="title">
						<expr value=".title-div"/>
					</attribute>
					<url />
				</concat>
			</extract-to>
			
			<extract-to field="f6">
				<concat>
					<replace pattern="(t)(\d)+" substitution="$2-$1">
						<text>
							<expr value="head > title"/>
						</text>
					</replace>
				</concat>
			</extract-to>
			<extract-to field="f6.1">
				<concat>
					<replace pattern="(.+?)T(.+)" substitution="$1">
						<attribute name="content">
							<expr value="meta[name=date]"/>
						</attribute>
					</replace>
				</concat>
			</extract-to>
			
			<extract-to field="f7">
				<concat>
					<text>
						<expr value="div.target"/>
					</text>
				</concat>
			</extract-to>
			<extract-to field="f8">
				<text>
					<first>
						<expr value="div.target"/>
					</first>
				</text>
			</extract-to>
			<extract-to field="f9">
				<size>
					<expr value="div.target"/>
				</size>
			</extract-to>
			<extract-to field="f10">
				<text>
					<last>
						<expr value="div.target"/>
					</last>
				</text>
			</extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir2" inherits="base">
			<extract-to field="f11">
				<constant value="t1" />
			</extract-to>
			<extract-to field="f12">
				<constant value="world!" />
			</extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir3">
			<partition>
				<expr value=".doc"/>
			</partition>
			<extract-to field="id">
				<concat>
					<attribute name="href">
					 	<expr value="a"/>
					 </attribute>
				</concat>
			</extract-to>
			<extract-to field="content">
				<concat>
					<text>
						<expr value="a" />
					</text>
				</concat>
			</extract-to>
		</document>
	</documents>
</config>

=== BayanGroup/nutch-custom-search/zal.extractor/src/test/resources/extractors-index-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd">
	<types>
		<type name="hello" converter="ir.co.bayan.simorq.zal.extractor.convert.TestConverter" />
	</types>
	<fields>
		<field name="f1" type="hello"/>
	</fields>
	<documents>
		<document url="^http://.+?\.blog.ir$" update="true">
			<extract-to field="f1">
				<constant value="t1" />
			</extract-to>
		</document>
	</documents>
</config>

=== BayanGroup/nutch-custom-search/zal.nutch.extractor/src/test/resources/extractors-css-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd">
	<types>
		<type name="hello" converter="ir.co.bayan.simorq.zal.nutch.extractor.TestConverter" />
	</types>
	<fields>
		<field name="f1" />
		<field name="f2" />
		<field name="f3" />
		<field name="f4" />
		<field name="f5" />
		
		<field name="f6" />
		<field name="f6.1" />
		
		<field name="f7" />
		<field name="f8" />
		<field name="f9" />
		<field name="f10" />
		
		<field name="f11" />
		
		<field name="f12" type="hello"/>
		
		<field name="id" />
		<field name="content" />
	</fields>
	<documents>
		<document id="base" url="^http://.+?\.blog.ir">
			<extract-to field="f1">
				<constant value="t1"/>
			</extract-to>
			<extract-to field="f2">
				<text>
					<expr value="head > title"/>
				</text>
			</extract-to>
			<extract-to field="f3">
				<attribute name="title">
					<expr value=".title-div"/>
				</attribute>
			</extract-to>
			<extract-to field="f4">
				<url />
			</extract-to>
			
			<extract-to field="f5">
				<concat>
					<constant value="t1"/>
					<text>
						<expr value="head > title"/>
					</text>
					<attribute name="title">
						<expr value=".title-div"/>
					</attribute>
					<url />
				</concat>
			</extract-to>
			
			<extract-to field="f6">
				<replace pattern="(t)(\d)+" substitution="$2-$1">
					<text>
						<expr value="head > title"/>
					</text>
				</replace>
			</extract-to>
			<extract-to field="f6.1">
				<replace pattern="(.+?)T(.+)" substitution="$1">
					<attribute name="content">
						<expr value="meta[name=date]"/>
					</attribute>
				</replace>
			</extract-to>
			
			<extract-to field="f7">
				<text>
					<expr value="div.target"/>
				</text>
			</extract-to>
			<extract-to field="f8">
				<text>
					<first>
						<expr value="div.target"/>
					</first>
				</text>
			</extract-to>
			<extract-to field="f9">
				<size>
					<expr value="div.target"/>
				</size>
			</extract-to>
			<extract-to field="f10">
				<text>
					<last>
						<expr value="div.target"/>
					</last>
				</text>
			</extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir2" inherits="base">
			<extract-to field="f11">
				<constant value="t1" />
			</extract-to>
			<extract-to field="f12">
				<constant value="world!" />
			</extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir3">
			<partition>
				<expr value=".doc"/>
			</partition>
			<extract-to field="id">
				<attribute name="href">
				 	<expr value="a"/>
				 </attribute>
			</extract-to>
			<extract-to field="content">
				<text>
					<expr value="a" />
				</text>
			</extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir4">
			<outlinks>
				<link>
					<partition>
						<expr value="a.outlink" />
					</partition>
					<href>
						<attribute name="href">
							<expr value="." />
						</attribute>
					</href>
					<anchor>
						<text>
							<expr value="." />
						</text>
					</anchor>
				</link>
			</outlinks>
		</document>
	</documents>
</config>

=== BayanGroup/nutch-custom-search/zal.extractor.core/src/test/resources/extractors-css-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd">
	<types>
		<type name="hello" converter="ir.co.bayan.simorq.zal.extractor.convert.TestConverter" />
	</types>
    <processors>
        <processor name="lower" class="ir.co.bayan.simorq.zal.extractor.process.Lower"/>
    </processors>
	<fields>
		<field name="f1" />
		<field name="f2" />
		<field name="f3" />
		<field name="f4" />
		<field name="f5" />
		
		<field name="f6" />
		<field name="f6.1" />
		
		<field name="f7" />
		<field name="f8" />
		<field name="f9" />
		<field name="f10" />
		
		<field name="f11" />
		
		<field name="f12" type="hello"/>
		
		<field name="url" />
		<field name="content" />
		
		<field name="multi" multi="true"/>
		<field name="no-multi" multi="false"/>

        <field name="to_lower" />
	</fields>
	<documents>
		<document id="base" url="^http://.+?\.blog.ir$">
			<extract-to field="f1">
				<constant value="t1"/>
			</extract-to>
			<extract-to field="f2">
				<text>
					<expr value="head > title"/>
				</text>
			</extract-to>
			<extract-to field="f3">
				<attribute name="title">
					<expr value=".title-div"/>
				</attribute>
			</extract-to>
			<extract-to field="f4">
				<url />
			</extract-to>
			
			<extract-to field="f5">
				<concat>
					<constant value="t1"/>
					<text>
						<expr value="head > title"/>
					</text>
					<attribute name="title">
						<expr value=".title-div"/>
					</attribute>
					<url />
				</concat>
			</extract-to>
			
			<extract-to field="f6">
				<replace pattern="(t)(\d)+" substitution="$2-$1">
					<text>
						<expr value="head > title"/>
					</text>
				</replace>
			</extract-to>
			<extract-to field="f6.1">
				<replace pattern="(.+?)T(.+)" substitution="$1">
					<attribute name="content">
						<expr value="meta[name=date]"/>
					</attribute>
				</replace>
			</extract-to>
			
			<extract-to field="f7">
				<text>
					<expr value="div.target"/>
				</text>
			</extract-to>
			<extract-to field="f8">
				<text>
					<first>
						<expr value="div.target"/>
					</first>
				</text>
			</extract-to>
			<extract-to field="f9">
				<size>
					<expr value="div.target"/>
				</size>
			</extract-to>
			<extract-to field="f10">
				<text>
					<last>
						<expr value="div.target"/>
					</last>
				</text>
			</extract-to>
			<extract-to field="content">
				<concat>
					<field-value field="f1" />
					<field-value field="f2" />
				</concat>
			</extract-to>
			
			<extract-to field="multi">
				<constant value="v1"/>
			</extract-to>
			<extract-to field="multi">
				<constant value="v2"/>
			</extract-to>
			
			<extract-to field="no-multi">
				<constant value="v1"/>
			</extract-to>
			<extract-to field="no-multi">
				<constant value="v2"/>
			</extract-to>

            <extract-to field="to_lower">
                <process processor="lower">
                    <constant value="HELLO"/>
                </process>
            </extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir2$" inherits="base">
			<extract-to field="f11">
				<constant value="t1" />
			</extract-to>
			<extract-to field="f12">
				<constant value="world!" />
			</extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir3$">
			<fragment root=".doc">
				<extract-to field="url">
					<attribute name="href">
					 	<expr value="a"/>
					 </attribute>
				</extract-to>
				<extract-to field="content">
					<text>
						<expr value="a" />
					</text>
				</extract-to>
			</fragment>
		</document>
		
		<document url="^http://.+?\.blog.ir4$">
			<outlinks>
				<for-each root="a.outlink">
					<link>
						<href>
							<resolve>
								<attribute name="href">
									<expr value="." />
								</attribute>
							</resolve>
						</href>
						<anchor>
							<text>
								<expr value="." />
							</text>
						</anchor>
					</link>
				</for-each>
			</outlinks>
		</document>
	</documents>
</config>

=== BayanGroup/nutch-custom-search/zal-extractor-core/src/test/resources/teste.xml
<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir http://raw.github.com/BayanGroup/nutch-custom-search/master/zal.extractor/src/main/resources/extractors.xsd">
    <fields>
        <field name="target" />
    </fields>
    <documents>
        <document url="." engine="css">
            <extract-to field="target">
                <raw>
                    <expr value="script" />
                </raw>
            </extract-to>
        </document>
    </documents>
</config>

=== BayanGroup/nutch-custom-search/zal.extractor/src/test/resources/extractors.xml
<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir http://raw.github.com/BayanGroup/nutch-custom-search/master/zal.extractor/src/main/resources/extractors.xsd" omitNonMatching="false">
    <types>
        <type name="long" converter="ir.co.bayan.simorq.zal.extractor.convert.LongConverter" />
    </types>
    <fields>
        <field name="num-items" type="long" />
        <field name="all-items" />
    </fields>
    <documents>
        <document url="^http://.+?\.google\.com/?$" engine="css">
            <extract-to field="num-items">
                <size>
                    <expr value=".gb1" />
                </size>
            </extract-to>
            <extract-to field="all-items">
                <truncate max="100">
                    <concat delimiter=",">
                        <text>
                            <expr value=".gb1" />
                        </text>
                    </concat>
                </truncate>
            </extract-to>
        </document>
    </documents>
</config>

=== BayanGroup/nutch-custom-search/zal.extractor/src/test/resources/extractors-xpath-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd"
	defaultEngine="xpath">
	<types>
		<type name="hello" converter="ir.co.bayan.simorq.zal.extractor.convert.TestConverter" />
	</types>
	<fields>
		<field name="f1" />
		<field name="f2" />
		<field name="f3" />
		<field name="f4" />
		<field name="f5" />
		
		<field name="f6" />
		<field name="f6.1" />
		
		<field name="f7" />
		<field name="f8" />
		<field name="f9" />
		<field name="f10" />
		
		<field name="f11" />
		
		<field name="f12" type="hello"/>
		
		<field name="url" />
		<field name="content" />
	</fields>
	<documents>
		<document id="d1" url="^http://.+?\.blog.ir">
			<extract-to field="f1">
				<text>
					<expr value="//book[@title='b1']" />
				</text>
			</extract-to>
			<extract-to field="f2">
				<concat delimiter="-">
					<text>
						<expr value="//book[@title]/@title" />
					</text>
				</concat>
			</extract-to>
			<extract-to field="f3">
				<text>
					<expr value="//b:book[@title='b1']"/>
				</text>
			</extract-to>
			<extract-to field="f4">
				<text>
					<expr value="//dns:book[@title='b3']"/>
				</text>
			</extract-to>
			<extract-to field="f5">
				<replace pattern="content(.*)" substitution="$1">
					<text>
						<expr value="//book[@title='b1']"/>
					</text>
				</replace>
			</extract-to>
		</document>
		<document id="d2" url="^http://.+?\.blog.ir2">
			<fragment root="//books/category[@name]">
				<extract-to field="url">
					<text>
						<expr value="./@name" />
					</text>
				</extract-to>
				<extract-to field="content">
					<text>
						<expr value=".//book" />
					</text>
				</extract-to>
			</fragment>
		</document>
		<document id="d3" url="^http://.+?\.blog.ir25" root="//books/category[@name]">
			<extract-to field="url">
				<text>
					<expr value="./@name" />
				</text>
			</extract-to>
			<extract-to field="content">
				<text>
					<expr value=".//book" />
				</text>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir3">
			<outlinks>
				<link root="//category[@name='c2']">
					<href>
						<resolve>
							<attribute name="title">
								<expr value="./book" />
							</attribute>
						</resolve>
					</href>
					<anchor>
						<text>
							<expr value="./book" />
						</text>
					</anchor>
				</link>
				<link>
					<href>
						<concat delimiter="/">
							<url />
							<constant value="sitemap.xml" />
						</concat>
					</href>
				</link>
			</outlinks>
		</document>
	</documents>
</config>
