=== BayanGroup/nutch-custom-search/zal.nutch.extractor/src/main/resources/extractors.xsd
<xs:schema attributeFormDefault="unqualified"
	elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://bayan.ir" xmlns="http://bayan.ir">

	<xs:complexType name="typeType">
		<xs:attribute type="xs:ID" name="name" use="required" />
		<xs:attribute type="xs:string" name="converter" use="optional" />
	</xs:complexType>

	<xs:complexType name="fieldType">
		<xs:attribute type="xs:ID" name="name" use="required" />
		<xs:attribute type="xs:IDREF" name="type" use="optional" />
	</xs:complexType>
	
	<xs:simpleType name="selectType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="first" />
			<xs:enumeration value="last" />
			<xs:enumeration value="all" />
			<xs:enumeration value="size" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:complexType name="selectorValue">
		<xs:attribute type="xs:string" name="selector" use="optional" />
		<xs:attribute type="xs:string" name="pattern" use="optional" />
		<xs:attribute type="xs:string" name="substitution" use="optional" />
		<xs:attribute type="selectType" name="select" use="optional" default="all"/>
		<xs:attribute type="xs:string" name="delimiter" use="optional"/>
	</xs:complexType>

	<xs:complexType name="contentType">
		<xs:complexContent>
			<xs:extension base="selectorValue">
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="attributeType">
		<xs:complexContent>
			<xs:extension base="selectorValue">
				<xs:attribute type="xs:string" name="name" use="required" />
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
	<xs:complexType name="xpathType">
		<xs:attribute type="xs:string" name="expression" use="optional" />
		<xs:attribute type="xs:string" name="pattern" use="optional" />
		<xs:attribute type="xs:string" name="substitution" use="optional" />
		<xs:attribute type="xs:string" name="delimiter" use="optional"/>
	</xs:complexType>

	<xs:complexType name="extractToType">
		<xs:sequence>
			<xs:choice maxOccurs="unbounded">
				<xs:element name="content" maxOccurs="unbounded" minOccurs="0" type="contentType" />
				<xs:element name="attribute" maxOccurs="unbounded" minOccurs="0" type="attributeType" />
				<xs:element name="xpath" maxOccurs="unbounded" minOccurs="0" type="xpathType" />
				<xs:element name="constant" maxOccurs="unbounded"  minOccurs="0" type="xs:string" />
			</xs:choice>
		</xs:sequence>
		<xs:attribute type="xs:IDREF" name="field" use="required" />
		<xs:attribute type="xs:string" name="delimiter" use="optional"/>
	</xs:complexType>

	<xs:complexType name="documentType">
		<xs:sequence>
			<xs:element name="extract-to" maxOccurs="unbounded" minOccurs="0" type="extractToType" />
		</xs:sequence>
		<xs:attribute type="xs:ID" name="id" use="optional" />
		<xs:attribute type="xs:string" name="url" use="optional" />
		<xs:attribute type="xs:IDREF" name="inherits" use="optional" />
		<xs:attribute type="xs:string" name="partition-by" use="optional"/>
		<xs:attribute type="xs:string" name="engine" use="optional" default="css"/>
	</xs:complexType>

	<xs:element name="config">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="types">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="type" maxOccurs="unbounded" minOccurs="0" type="typeType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="fields">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="field" maxOccurs="unbounded" minOccurs="0" type="fieldType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="documents">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="document" maxOccurs="unbounded" minOccurs="0" type="documentType" />
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="omitNonMatching" type="xs:boolean" default="true"/>
			<xs:attribute name="defaultEngine" type="xs:string" default="css"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BayanGroup/nutch-custom-search/zal.nutch.extractor/src/test/resources/extractors-xpath-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd">
	<types>
		<type name="hello" converter="ir.co.bayan.simorq.zal.nutch.extractor.TestConverter" />
	</types>
	<fields>
		<field name="f1" />
		<field name="f2" />
		<field name="f3" />
		<field name="f4" />
		<field name="f5" />
		
		<field name="f6" />
		<field name="f6.1" />
		
		<field name="f7" />
		<field name="f8" />
		<field name="f9" />
		<field name="f10" />
		
		<field name="f11" />
		
		<field name="f12" type="hello"/>
		
		<field name="id" />
		<field name="content" />
	</fields>
	<documents>
		<document id="base" url="^http://.+?\.blog.ir">
			<extract-to field="f1">
				<constant>t1</constant>
			</extract-to>
			<extract-to field="f2">
				<content selector="head > title"/>
			</extract-to>
			<extract-to field="f3">
				<attribute selector=".title-div" name="title" />
			</extract-to>
			<extract-to field="f4">
				<content selector="url" />
			</extract-to>
			
			<extract-to field="f5">
				<constant>t1</constant>
				<content selector="head > title"/>
				<attribute selector=".title-div" name="title" />
				<content selector="url" />
			</extract-to>
			
			<extract-to field="f6">
				<content selector="head > title" pattern="(t)(\d)+" substitution="$2-$1"/>
			</extract-to>
			<extract-to field="f6.1">
				<attribute name="content" selector="meta[name=date]" pattern="(.+?)T(.+)" substitution="$1"/>
			</extract-to>
			
			<extract-to field="f7">
				<content selector="div.target" select="all"/>
			</extract-to>
			<extract-to field="f8">
				<content selector="div.target" select="first"/>
			</extract-to>
			<extract-to field="f9">
				<content selector="div.target" select="size"/>
			</extract-to>
			<extract-to field="f10">
				<content selector="div.target" select="last"/>
			</extract-to>
			
		</document>
		
		<document url="^http://.+?\.blog.ir2" inherits="base">
			<extract-to field="f11">
				<constant>t1</constant>
			</extract-to>
			<extract-to field="f12">
				<constant>world!</constant>
			</extract-to>
		</document>
		
		<document url="^http://.+?\.blog.ir3" partition-by=".doc">
			<extract-to field="id">
				<attribute name="href" selector="a" />
			</extract-to>
			<extract-to field="content">
				<content selector="a" />
			</extract-to>
		</document>
	</documents>
</config>

=== BayanGroup/nutch-custom-search/zal.nutch.extractor/src/test/resources/extractors-index-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd">
	<types>
		<type name="hello" converter="ir.co.bayan.simorq.zal.nutch.extractor.TestConverter" />
	</types>
	<fields>
		<field name="f1" type="hello"/>
	</fields>
	<documents>
		<document url="^http://.+?\.blog.ir">
			<extract-to field="f1">
				<constant>t1</constant>
			</extract-to>
		</document>
	</documents>
</config>

=== BayanGroup/nutch-custom-search/zal.nutch.extractor/src/test/resources/extractors-config-test.xml
<?xml version="1.0" encoding="UTF-8"?>

<config xmlns="http://bayan.ir" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://bayan.ir extractors.xsd"
	omitNonMatching="true">
	<types>
		<type name="long" converter="ir.co.bayan.simorq.zal.nutch.extractor.convert.LongConverter" />
		<type name="persian_date" converter="ir.co.bayan.simorq.zal.nutch.extractor.convert.PersianDateConverter"/>
		<type name="persian_long" converter="ir.co.bayan.simorq.zal.nutch.extractor.convert.PersianLongConverter"/>
	</types>
	<fields>
		<field name="post-title" />
		<field name="post-body" />
		<field name="post-date" type="persian_date"/>
		<field name="post-comments" />
		<field name="document-type" />
		<field name="blog-title" />
		<field name="blog-sub-title" />
		<field name="blog-author" />
	</fields>
	<documents>
		<document id="post-page">
			<extract-to field="post-title">
				<content selector="div.post > div.title > h2 > a"/>
			</extract-to>
			<extract-to field="post-body">
				<content selector="div.post > div.body > div.cnt" />
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir/\d{4}/\d{2}/\d{2}/.+" inherits="post-page">
			<extract-to field="post-date" >
				<content selector="url" pattern="^http://.+?\.blog.ir/(\d{4})/(\d{2})/(\d{2})/.+" substitution="$1-$2-$3"/>
			</extract-to>
			<extract-to field="post-comments">
				<content selector="div.post_comments > div.body_cmt > div.cnt > span.cnt_l" />
				<content selector="div.cmt_reply" pattern="^(پاسخ:)?(.*)" substitution="$2" />
			</extract-to>
			<extract-to field="document-type">
				<constant>Post</constant>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir/page/.+" inherits="post-page">
			<extract-to field="document-type">
				<constant>Custom-Page</constant>
			</extract-to>
		</document>
		<document url="^http://.+?\.blog.ir">
			<extract-to field="blog-title">
				<content selector="div.title_desc > h1 > a" />
				<content selector="url" pattern="^http://(.+?)\.blog.ir" substitution="$1"/>
			</extract-to>
			<extract-to field="blog-sub-title">
				<content selector="div.desc > h2" />
			</extract-to>
			<extract-to field="blog-author">
				<content selector="span.author2" select="first"/>
			</extract-to>
			<extract-to field="document-type">
				<constant>First-Page</constant>
			</extract-to>
		</document>
	</documents>
</config>
